spring:
  resources:
    static-locations:
    - file:/data/html
    - classpath:/META-INF/resources/swagger-ui.html
    - classpath:/META-INF/resources/springfox-swagger-ui/
  datasource:
    url: jdbc:mysql://192.168.1.113/nuls?useSSL=false
    username: root
    password: dbadmin@2018
    driver-class-name: com.mysql.jdbc.Driver
logging:
  config: classpath:logger/app-dev.xml
#app config
app:
  devMode: true